### ISSUE TITLE
apollo-vscode: localSchemaFile not loaded relatively to apollo.config.js file in multi root workspace

### ISSUE THREAD

**Issue by iki** [apollographql/apollo-tooling#1666] opened 2019-11-19 12:20 UTC
**Intended outcome:**

Local schema file should be loaded relatively to apollo.config.js file in multi root workspace.

**Actual outcome:**

```Error: Unable to read file ./schema.graphql. ENOENT: no such file or directory, open './schema.graphql'```

**How to reproduce the issue:**

1. create multi root workspace
2. in one of the roots, create an `apollo.config.js` with relative `localSchemaFile` path, e.g.
```
module.exports = {
  client: {
    service: {
      name: 'schemafile',
      localSchemaFile: './schema.graphql'
    }
  }
}
```
3. open any file from the given root

See, also the original report https://github.com/apollographql/apollo-tooling/issues/669#issuecomment-484400735 by @kazinad and temporary workaround https://github.com/apollographql/apollo-tooling/issues/669#issuecomment-551451092 by @joltmode

**Versions**

Tested in current version `2.21.0`.

**Comment by JakeDawkins** [comment] 2019-11-20 15:40
Hi @iki! Thanks for asking about this.

Multi-root workspaces aren't currently supported with the vscode extension (see #821). I confirmed that this feature isn't broken on normal projects. 

I noticed the `versions` you listed was a CLI version. Do you have the same issue with localSchemaFile on the latest version of the CLI, or just vscode?

Since this is a known issue with the extension that's already discussed elsewhere, I'll close this issue unless there are CLI issues as well that need investigation :)

**Closed by JakeDawkins** 2019-11-20 15:40 UTC

**Comment by iki** [comment] 2019-11-27 21:29
@JakeDawkins  `apollo` CLI works ok, it resolves the relative `localSchemaFile` path correctly, even when run from a different directory.

Looking at #821, it reported exactly the same issue already. Let's continue there.

**Comment by yoavbls** [comment] 2024-08-06 19:54
Until `localSchemaFile` will be relative to the file you can use this workaround:
 ```ts
module.exports = {
  client: {
    service: {
      name: 'schemafile',
      localSchemaFile: `${__dirname}/schema.graphql`
    }
  }
}
```
