### ISSUE TITLE
[PNPM] Error: Cannot find module 'strip-ansi'

### ISSUE THREAD

**Issue by martinjlowm** [apollographql/apollo-tooling#1086] opened 2019-03-07 19:48 UTC
Version 1.x of `@oclif/plugin-help` is missing `strip-ansi` as a dependency (listed as devDependency instead).

It has been fixed with version 2.1.2 as noted here: https://github.com/oclif/plugin-help/issues/31

**Intended outcome:**

No fatal error on CLI launch.

**Actual outcome:**

```
$ apollo --help
Error: Cannot find module 'strip-ansi'
```

**How to reproduce the issue:**

Install Apollo 2.6.0 (newest version as of this writing) with a strict package manager, e.g. pnpm and run `apollo --help`.

**Versions**

2.6.0

**Comment by trevor-scheer** [comment] 2019-07-12 17:44
@martinjlowm, thanks for submitting an issue! It looks like our version of `@oclif/plugin-help` is above the version you mentioned at this point in time. I'm going to close this issue, but please feel free to reopen if the issue is still ongoing.

**Closed by trevor-scheer** 2019-07-12 17:44 UTC
