### ISSUE TITLE
Is Engine required?

### ISSUE THREAD

**Issue by jedrichards** [apollographql/apollo-tooling#1075] opened 2019-03-05 10:58 UTC
Is it possible to use these tools without using the Engine service at all? I can successfully run commands on my client project with a valid `ENGINE_API_KEY`, but as soon as I remove it I run into problems.

Trying to run `apollo client:check` without an api key env var, against a live server on a `url` with the following config:

```
module.exports = {
  client: {
    service: {
      url: 'http://...',
    },
    includes: ['src/**/*.graphql'],
  },
}
```

Results in an error: `No service found to link to Engine`. If I add an arbitrary `name`,

```
module.exports = {
  client: {
    service: {
      name: 'foo',
      url: 'http://...',
    },
    includes: ['src/**/*.graphql'],
  },
}
```

I get an error: `Unable to find ENGINE_API_KEY`.

Using a `localSchemaFile` results in no joy either.

**Comment by JakeDawkins** [comment] 2019-03-05 15:41
Hi @jedrichards! For future reference, the [apollo spectrum community](https://spectrum.chat/apollo) would be the place to go to get questions like this answered more quickly (since there are more than a few people watching). We'd like to keep these issues reserved for bug reports or feature requests.

But to answer your question here, No, Engine is not required to do client:check 😄 

The instructions for setting up a client to use a local endpoint or schema file are [here](https://www.apollographql.com/docs/references/apollo-config.html#client-service). Make sure you're up to date with the CLI and that there **isn't a .env file (even empty) or a key in your env** or else the CLI _may_ parse the env for the key instead of using the local endpoint.

I'll close this since I can't reproduce locally, but if it turns out to be a bug, I can reopen :)

**Closed by JakeDawkins** 2019-03-05 15:41 UTC

**Comment by jedrichards** [comment] 2019-03-05 15:58
@JakeDawkins I believe this to be a bug. I've created a minimal repro repository here: https://github.com/jedrichards/apollo-tooling-1075 (sent an invite to collaborate).

**Comment by JakeDawkins** [comment] 2019-03-05 20:18
@jedrichards oops! Sorry, I was confused. _Yes_ engine is required for the client:check command. The reason is that operation validation isn't something done locally by the language server. It's handled on the server-side of engine.

The CLI fires a mutation containing the client operations and those operations are validated against the most recently published schema. There's no easy way to make this a client-run command, as it would require a lot of duplicated work all across the board. So I don't believe this will be a feature than can be supported without Engine anytime soon.

**Comment by jedrichards** [comment] 2019-03-07 10:49
@JakeDawkins Ah ok, thanks for checking and updating the messaging 👍
