### ISSUE TITLE
apollographql.vscode-apollo fails to load in projects with . period in path

### ISSUE THREAD

**Issue by DonaldWebb** [apollographql/apollo-tooling#838] opened 2018-12-18 05:44 UTC
apollographql.vscode-apollo 1.2.7
**Intended Outcome:**
1. VSCode Open Project with . in path. eg. c:/dev/product.client/
2. apollographql.vscode-apollo loads and provides autocomplete info 

**Actual Outcome:**
Extension fails to load and no autocomplete provided. After removing the **.** the extension loads and provides autocomplete.
It looks like it is trying to load the project folder as a file of type .client
Extension output:
```
Error: No loader specified for extension ".client", so searchPlaces item "c:/projects/test.client" is invalid
    at config.searchPlaces.forEach.place (c:\Users\user\.vscode\extensions\apollographql.vscode-apollo-1.2.7\node_modules\cosmiconfig\dist\createExplorer.js:64:15)
    at Array.forEach (<anonymous>)
    at Explorer.validateConfig (c:\Users\user\.vscode\extensions\apollographql.vscode-apollo-1.2.7\node_modules\cosmiconfig\dist\createExplorer.js:60:25)
    at new Explorer (c:\Users\user\.vscode\extensions\apollographql.vscode-apollo-1.2.7\node_modules\cosmiconfig\dist\createExplorer.js:31:10)
    at createExplorer (c:\Users\user\.vscode\extensions\apollographql.vscode-apollo-1.2.7\node_modules\cosmiconfig\dist\createExplorer.js:298:20)
    at cosmiconfig (c:\Users\user\.vscode\extensions\apollographql.vscode-apollo-1.2.7\node_modules\cosmiconfig\dist\index.js:48:10)
    at Object.exports.loadConfig (c:\Users\user\.vscode\extensions\apollographql.vscode-apollo-1.2.7\node_modules\apollo-language-server\lib\config.js:134:22)
    at LanguageServerLoadingHandler.handle (c:\Users\user\.vscode\extensions\apollographql.vscode-apollo-1.2.7\node_modules\apollo-language-server\lib\workspace.js:66:47)
    at Array.from.map.configFolder (c:\Users\user\.vscode\extensions\apollographql.vscode-apollo-1.2.7\node_modules\apollo-language-server\lib\workspace.js:73:11)
    at Array.map (<anonymous>)
```

apollo.config.js
```JavaScript
module.exports = {
  client: {
    excludes: ["./src/generated-models.tsx", "./dist/**", "./public/**"],
    service: {
      endpoint: "http://localhost:4100/graphql",
      name: "example",
      url: "http://localhost:4100/graphql",
    },
  },
};
```
```
Vscode:
Version: 1.30.0 (user setup)
Commit: c6e592b2b5770e40a98cb9c2715a8ef89aec3d74
Date: 2018-12-11T22:29:11.253Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
OS: Windows_NT x64 10.0.17134
```

**Reproduce:**
1. Load valid project with . in project path in VScode with apollographql.vscode-apollo  extension.
2. Extension fails to load with above error
3. Remove . from path
4. Extension loads correctly and provides autocomplete

**Comment by mhabegger** [comment] 2018-12-29 22:51
I can confirm the issue.
It seems, however, the exception is thrown by the underlying dependency: cosmiconfig.

Looking into the code of `vscode-apollo` the method `getSearchPlaces` adds the local directory to the array of places to search for the config. Here: https://github.com/apollographql/apollo-tooling/blob/16c70514917006d836d177b6da1d6f8b79cb2505/packages/apollo-language-server/src/config.ts#L123

Which in turn bubbles up from here https://github.com/apollographql/apollo-tooling/blob/814819d86c1c0629040c2f05aa5dfc48db1c88b5/packages/apollo-language-server/src/workspace.ts#L126

So it seems to be tied up higher in Apollo components.
Temporarly modifing the locally installed plugin code in `~/.vscode/extensions/apollographql.vscode-apollo-1.2.7/node_modules/apollo-language-server/lib/config.js:135` to `searchPlaces: getSearchPlaces(),` or renaming the directory so it does not contain a dot works.

**Comment by dead** [comment] 2019-02-03 14:18
@JakeDawkins 
When the version 1.4.4 is going to be released in the vscode marketplace?

**Comment by JakeDawkins** [comment] 2019-02-03 15:49
@dead I just published it! That _should_ resolve this issue. We can reopen if not!

**Closed by JakeDawkins** 2019-02-03 15:49 UTC
