### ISSUE TITLE
VSCode Plugin: Loading Schema Twice

### ISSUE THREAD

**Issue by alexlafroscia** [apollographql/apollo-tooling#801] opened 2018-12-04 21:32 UTC
It seems like the schema is being loaded twice by the VSCode plugin. As soon as I load the plugin, I get the following error:

> Type "AddLinkPayload" already exists in the schema. It cannot also be defined in this type definition. 

This is the first type in my schema, and is only defined once in the file. This is leading me to think that the file is attempting to be loaded more than once, adding to the existing schema and causing the error.

**Comment by alexlafroscia** [comment] 2018-12-04 21:43
This is where the error is coming from:

https://github.com/apollographql/apollo-tooling/blob/5d1cb7a22e001d036145dd275104eaf162dd4e55/packages/apollo-language-server/src/project/client.ts#L140

**Comment by alexlafroscia** [comment] 2018-12-04 21:49
I currently have a configuration that looks like this:

```javascript
module.exports = {
  client: {
    includes: [
      './packages/original-series-engine/addon/**/*.graphql',
      './packages/original-series-engine/addon/**/*.js'
    ],
    service: {
      name: 'Original Series Workflow API',
      localSchemaFile:
        './packages/original-series-engine/addon/graphql/schema.graphql'
    }
  }
};
```

The documentation seems to suggest that I could leave out my `service` definition here, because 

>[By default, the VS Code extension will look for all files under `./src` to find both the operations and schema definitions for building a complete schema for the application.](https://www.apollographql.com/docs/platform/editor-plugins.html#client-side-schemas)

But in practice, that doesn't work, as I get a complaint that

> No provider was created for config

**Comment by igorp1** [comment] 2018-12-17 14:06
were you able to find a solution to this @alexlafroscia? I'm running into the same issue

**Comment by alexlafroscia** [comment] 2018-12-17 17:46
Nope, unfortunately not. I've been flip-flopping between this and the Prisma VSCode plugin, because both have issues for me. I'm currently on the Prisma one, which is working a little better!

**Comment by igorp1** [comment] 2018-12-17 17:54
I've been doing a lot of back and forth between those 2 as well. I think our issue might be solved with the next release based on this [commit](https://github.com/apollographql/apollo-tooling/commit/d348b58b64d25455c441af74a16a31a6a4c6ed98) that documents our use case with service nested into client. It is tagged with `vscode-apollo@1.2.8` current extension version is 1.2.7, so... fingers crossed.

Would you mind sharing what you have on your .graphqlconfig to get the Prima extension to work properly?

**Comment by alexlafroscia** [comment] 2018-12-17 18:53
Sure -- not that this is specific to our application in some ways, which is a monorepo of Ember packages

```json
{
  "projects": {
    "indie-engine": {
      "schemaPath": "packages/indie-engine/addon/graphql/schema.graphql",
      "includes": ["packages/indie-engine/addon/**/*.*"],
      "excludes": [
        "packages/indie-engine/addon/graphql/schema.graphql",
        "packages/indie-engine/addon/graphql/fragments.js"
      ],
      "extensions": {
        "endpoints": {
          "dev": "http://localhost:3001/api/workflow/graphql/",
          "test": "http://localhost:4200/api/workflow/graphql/"
        },
        "generate-fragments": {
          "output": "packages/indie-engine/addon/graphql/fragments.js",
          "generator": "js"
        }
      }
    },
    "original-series-engine": {
      "schemaPath": "packages/original-series-engine/addon/graphql/schema.graphql",
      "includes": ["packages/original-series-engine/addon/**/*.*"],
      "excludes": [
        "packages/original-series-engine/addon/graphql/schema.graphql"
      ],
      "extensions": {
        "endpoints": {
          "test": "http://localhost:4200/api/workflow/original-series/graphql"
        }
      }
    },
    "workflow-components": {
      "schemaPath": "packages/workflow-components/tests/graphql/schema.graphql",
      "includes": ["packages/workflow-components/addon/**/*.*"],
      "extensions": {
        "endpoints": {
          "test": "http://localhost:4200/api/workflow/original-series/graphql"
        }
      }
    }
  }
}
```

**Comment by igorp1** [comment] 2018-12-17 18:55
Thank you for sharing @alexlafroscia, this is def helpful

**Comment by JakeDawkins** [comment] 2019-03-11 17:03
Sorry we haven't responded to this until now! Has this issue been resolved in the past couple months?

**Comment by Hotell** [comment] 2019-03-12 09:56
it's not loading just twice... 3 times in my project and it doesn't work either. it still uses old schema...

![bug-apollo-client-loaded-3-times](https://user-images.githubusercontent.com/1223799/54191001-4e017b00-44b5-11e9-8767-67f5087a7bac.gif)

**Comment by JakeDawkins** [comment] 2019-03-18 15:11
@Hotell Are you also getting the error for it trying to overwrite existing types or just the multiple loading notifications?

**Comment by benmosher** [comment] 2019-03-29 11:57
@JakeDawkins I just installed the VSCode extension this morning and am seeing this issue.

I am working around the error with 
```js
module.exports = {
  client: {
    service: {
      name: 'my-schema',
      localSchemaFile: './src/schema.graphql',
    },
    // hack: remove .graphql from includes to avoid duplicate schema errors
    includes: ['./src/**/*.{ts,js,tsx}'],
  },
}
```

but I think this has the effect of disabling the language features when editing the schema itself. They work great from the `gql` tag in JS/TS source now, though, and no errors in the extension console.

**Comment by JakeDawkins** [comment] 2019-04-02 14:03
@benmosher @alexlafroscia It looks like both of your issues are from the language server trying to load the schema from `localSchemaFile` and running into it again because it matches the `includes` glob, which by default picks up `graphql` files in `src/` 

A Workaround for this would be to either move the schema outside of src (which we do usually) or to add an item under the `excludes` key to explicitly prevent reloading of the schema.

A more permanent fix would be to track the URIs of the loaded schema files to make sure there's no accidental reload, but I'll have to look into that. I'm not sure how much extra work would be required yet.

**Comment by JakeDawkins** [comment] 2019-04-02 14:10
Also, quick note, we don't fully support editing schema files right now. So things like typeahead and type information in schema files loaded by `localSchemaFile` _shouldn't_ work (although we need to add support for that soon 🙂).

**Comment by damassi** [comment] 2019-04-21 06:39
Nice! Explicitly excluding the local schema in `excludes` while pointing to remote schema works great.

**Comment by dylanwulf** [comment] 2019-05-06 16:37
I am getting this issue whenever I open a file diff that contains typeDefs from the source control sidebar

**Comment by DanielHabenicht** [comment] 2019-06-23 01:56
That's really inconvenient and renders the plugin useless for me. 

@JakeDawkins 
1. In my project that does not work. I am working in a Monorepo and have put the `apollo.config.js` in my root, so there is no `./src` folder. The `.graphql` file (in one of the project folder roots, but definitely not in a `src` folder) is picked up by the extension nevertheless. 

2. Does not work as described here: https://github.com/apollographql/apollo-tooling/issues/812#issuecomment-456925234

3. That's not working if you only want to work with the local `schema.graphql` as the extension complains if no `localSchemaFile` is provided.

**Comment by JakeDawkins** [comment] 2019-06-26 16:22
I'm sorry you're still seeing this @DanielHabenicht. I'm not sure what's going on. Is there a repo you can point me to with the reproduction of this? 

Does your monorepo have multiple apollo projects inside it? If so, having a single apollo config at the root of the _repo_ won't work. Config files only support single projects.

Maybe you could also paste in your config here to help me figure out what's going on.

**Comment by joefiorini** [comment] 2019-07-05 13:45
FWIW I'm seeing this same issue loading a project that gets the schema from an endpoint URL instead of `localSchemaFile`. I do not have a schema file under `src` and currently my config specifically only includes `ts` & `tsx` files and excludes any `graphql` files. Here's the config:

```javascript
module.exports = {
  client: {
    service: {
      name: "feature-keeper-api",
      endpoint: {
        url: "http://localhost:8000/.netlify/functions/graphql",
      },
    },
    includes: ["./src/**/*.{ts,tsx}"],
    excludes: [
      "./src/**/.test.{ts,tsx}",
      "./src/@types",
      "./src/functions",
      "**/*.graphql",
    ],
  },
}
```

I also see the error running `client:codegen` which is the majority reason I am using `apollo-cli`.

**Comment by lorensr** [comment] 2019-08-08 07:14
This was fixed for me by adding excludes. From:

```js
module.exports = {
  client: {
    service: {
      name: 'api',
      url: 'http://localhost:4000/'
    }
  }
}
```

to:

```js
module.exports = {
  client: {
    service: {
      name: 'api',
      url: 'http://localhost:4000/'
    },
    excludes: ['**/*.graphql']
  }
}
```

**Comment by tvvignesh** [comment] 2019-11-10 14:35
@JakeDawkins I have been struggling with the same problem as well. Adding excludes did not solve the problem for me (may be because I am using the registry?)

**I am using the Apollo Schema Registry with Apollo Federation**

My apollo.config.js looks like this:

```
module.exports = {
    client: {
        service: 'tctest-2@poc',
        excludes: [
            '**/*.gql',
            '**/*.graphql',
            '**/node_modules/**/*',
            '**/__tests___/**/*'
        ]
    }
};
```

Screenshot of the error in vscode apollo graphql extension:

![Screenshot from 2019-11-10 19-51-02](https://user-images.githubusercontent.com/1165845/68545466-713d4b00-03f3-11ea-84c8-5e9dc7bb600f.png)

The VSCode extension keeps restarting again and again for 5 times and then it says the server will not be restarted (screenshot below). Then I have to restart the window again to get it back up. Suggestions work until it crashes.

![Screenshot from 2019-11-10 19-55-01](https://user-images.githubusercontent.com/1165845/68545541-11936f80-03f4-11ea-822c-5bf8b75d3e3d.png)

This is the version of libraries I am using:

```
    "apollo-cache-inmemory": "^1.6.3",
    "apollo-client": "^2.6.4",
    "apollo-link-http": "^1.5.16",
    "graphql": "^14.5.8",
    "graphql-tag": "^2.10.1"
```

Thanks in advance.

**Comment by tvvignesh** [comment] 2019-11-10 16:38
> @JakeDawkins I have been struggling with the same problem as well. Adding excludes did not solve the problem for me (may be because I am using the registry?)
> 
> **I am using the Apollo Schema Registry with Apollo Federation**
> 
> My apollo.config.js looks like this:
> 
> ```
> module.exports = {
>     client: {
>         service: 'tctest-2@poc',
>         excludes: [
>             '**/*.gql',
>             '**/*.graphql',
>             '**/node_modules/**/*',
>             '**/__tests___/**/*'
>         ]
>     }
> };
> ```
> 
> Screenshot of the error in vscode apollo graphql extension:
> 
> ![Screenshot from 2019-11-10 19-51-02](https://user-images.githubusercontent.com/1165845/68545466-713d4b00-03f3-11ea-84c8-5e9dc7bb600f.png)
> 
> The VSCode extension keeps restarting again and again for 5 times and then it says the server will not be restarted (screenshot below). Then I have to restart the window again to get it back up. Suggestions work until it crashes.
> 
> ![Screenshot from 2019-11-10 19-55-01](https://user-images.githubusercontent.com/1165845/68545541-11936f80-03f4-11ea-822c-5bf8b75d3e3d.png)
> 
> This is the version of libraries I am using:
> 
> ```
>     "apollo-cache-inmemory": "^1.6.3",
>     "apollo-client": "^2.6.4",
>     "apollo-link-http": "^1.5.16",
>     "graphql": "^14.5.8",
>     "graphql-tag": "^2.10.1"
> ```
> 
> Also, I see Apollo GraphQL listed twice in the Outputs section of VSCode (similar to what is mentioned here: [#690 (comment)](https://github.com/apollographql/apollo-tooling/issues/690#issuecomment-461882741)) - Is it loading once for registry and once for local graphql files?
> 
> Thanks in advance.

Finally got it solved. It was because I was writing my code in Typescript in src (.ts) and it was getting built to javascript in dist (.js) and Apollo GQL was going through both of these causing the duplication. I added `'**/dist/**/*.js',` to excludes and then it worked.

**Comment by tdnghia98** [comment] 2020-03-05 09:23
So weird that the issue is still not resolved

**Comment by niclaspallin** [comment] 2020-05-30 11:00
Im having this issue as well. I tried most combinations in apollo.config.js. I finally got it to work, I'm not sure how it finds all the schema definitions but I have an isomorphic react app, so the way I solved it was to only include files under the client directory, excluding all server files.

**Comment by JakeDawkins** [comment] 2020-06-03 21:03
@niclaspallin the current config setup only really allows for a single project per apollo config file. so if you have a service and a client project under a single apollo.config glob, it makes sense why this error would be happening for you.

**Comment by abstractmachines** [comment] 2020-07-02 20:16
> 1. move the schema outside of src (which we do usually)

Hey @JakeDawkins :) Thanks for answering all these questions! 

Still having issues with a simple app setup for this feature, and excluding `localSchema` does not seem to work; multiple permutations of `include/exclude` don't seem to work either. 

The primary issue I'm noticing here is that developers using the VSCode/Apollo extension don't seem to have a correct "mental model" of how the schema/definition files are found/resolved by the extension (and I see that issue echoed above in comments such as "I'm not sure how it finds all the schema definitions..."). Once I/we get a "mental model" of how the files are resolved/found/located, I think it'll be easier to denote the lines of "if local schema, do A, if remote/Studio schema, do B."

I have 4 questions:

1. Is there a simple, bare-bones setup that you recommend for "remote/Apollo Studio schema only, and totally ignore the local schema", just to keep it simple?
2. Are the `apollo.config.js` `paths` for `include/exclude` relative to root dir of project, or, are the paths relative to `./root/src/`?
3. Does the extension expect that schema.js/.json/.graphql/other formats, be located at `./rootdir/src/schema`?
4. Perhaps the silliest question: When you say "move the schema outside of src dir", you mean `schema.graphql` (the generated SDL file) and/or `schema.json` (a JSON introspection result), _not_ `schema.js`, correct?

**Comment by HosseinAgha** [comment] 2020-12-16 17:07
> remove the localSchemaFile entry under service, and let the language server find the schema by itself using includes.   

@JakeDawkins Doing this generates the following error for me:  
`Service stats could not be loaded. This may be because you're missing an apollo.config.js file or it is misconfigured. For more information about configuring Apollo projects, see the guide here (https://go.apollo.dev/t/config).`   

My serverside schema is defined in `.gql` files and I don't have any client-side for now. I tried reading the schema from my GraphQL service and excluding the `.gql` files in `src` but the language server will be disabled for those files.  

```js
module.exports = {
  client: {
    excludes: ['src/**/*.gql'],
    service: {
      name: 'local',
      url: 'http://localhost:port/graphql',
    },
  },
};
```

So if I exclude the files I get nothing from the language server (no jump to definition, no autocomplete) and if I remove the service definition I get the above error.

**Comment by macrozone** [comment] 2021-02-15 15:37
i am also shocked by the current state of the vscode extension. It sometimes work, and when it works its fantastic, but as soon as it gets a bit more complicated like having a project that requires two graphql endpoints, it fails and in a very weird and inconsistent way.

I tried to configure two apollo.config.js, but that leads to strange hard to reproduce errors.

Also just having one apollo.config.js and adding excludes to ignore queries that use the other graphql endpoint does not work at all. excludes seem to have no effect at all.

I think this needs a major overhowl and maybe the maintainers need to dog-feed it to themselves (in particular the multi-endpoint use-case). 

If the core team cannot maintain it, it would be fair for the community that this is announced accordingly.

**Comment by haf** [comment] 2021-09-07 08:41
Related https://github.com/hasura/graphql-engine/issues/6466

**Comment by haf** [comment] 2021-09-07 08:44
From the comments I realised that it reads the schema file twice if that file is under `src/`

<img width="379" alt="image" src="https://user-images.githubusercontent.com/193115/132314090-4e77328f-5137-4c4f-bd37-cead83a5c8e0.png">

Just exclude it:

<img width="620" alt="image" src="https://user-images.githubusercontent.com/193115/132314151-ebe57a8c-c806-4a24-aae3-39cd879969d1.png">

**Comment by jgzuke** [comment] 2021-10-06 02:02
Realizing I forgot to come back to close this! This was fixed and released a while ago in https://github.com/apollographql/vscode-graphql/pull/8. If you're still seeing this error please open a new issue over on [the new repo](https://github.com/apollographql/vscode-graphql)! Thanks for all the help investigating 😄

**Closed by jgzuke** 2021-10-06 02:02 UTC
Labels: :spiral_notepad: component - vscode
