### ISSUE TITLE
[vscode-apollo] auto-completion alert of GraphQLString type

### ISSUE THREAD

**Issue by vreality64** [apollographql/apollo-tooling#862] opened 2018-12-28 08:19 UTC
### Issue Description
- VSCode OUTPUT was shown on auto-completing `String` types

You can see `userName`'s type is `String`. when I auto-complete in `userName` parenthesis, VSCode's OUTPUT was shown which is not what I expected. It feels like noise.

I thinks red underline is enough. It's simple and enough noticeable.

![auto completion alert](https://user-images.githubusercontent.com/886706/50507938-07f66700-0ac3-11e9-8e11-368cf4883b68.gif)

**Comment by trevor-scheer** [comment] 2019-05-15 00:36
Hey @vreality64, thanks for submitting this issue! Are you still seeing this? I was unable to reproduce - it's possible it was resolved via some error handling elsewhere in the language server.

**Comment by trevor-scheer** [comment] 2019-06-02 21:22
Closing due to inactivity, but feel free to re-open

**Closed by trevor-scheer** 2019-06-02 21:22 UTC
