### ISSUE TITLE
Code generation from both `.graphql` and `.tsx` files

### ISSUE THREAD

**Issue by irace** [apollographql/apollo-tooling#706] opened 2018-11-14 23:05 UTC
I’m trying to figure out how to get `apollo codegen:generate` to support both queries in separate `.graphql` files _plus_ queries in inline `gql` inside of TypeScript files.

If i pass a `--queries=src/**/*.graphql` argument, it pulls in the `.graphgl` files but doesn’t look into the `.tsx` files for inline `gql` queries.

If I do not not pass any `--queries`` argument, it pulls in the inline `gql` queries from the `.tsx` files but doesn’t look into the `.graphgl` files.

I tried targeting both by passing `--queries=src/**/*.{graphql,tsx}` but it didn’t work. 

I also tried doing two `apollo codegen:generate` passes, one with `--queries` and one without, and while this _almost_ accomplished what I was hoping for, the second pass clobbered the `globalTypes.ts` file generated by the first pass.

Any ideas?

**Comment by danilobuerger** [comment] 2018-11-15 11:01
This seems to be a regression from https://github.com/apollographql/apollo-tooling/commit/d2d73f9c597845355b7ee267e411d80d1c493043

@jbaxleyiii  Why was the `queries` param removed from non-watch building in your monster commit, you sinner 😂?

**Comment by trevor-scheer** [comment] 2018-11-16 02:57
@irace is the config file an option for you? As @danilobuerger, currently the `--queries` flag is only used in watch mode.

```
// apollo.config.js
module.exports = {
  client: {
    ...
    include: ['**/*.{graphql, tsx}']
  }
}
```

**Comment by irace** [comment] 2018-11-16 03:55
@trevor-scheer Hmmm... I'm not sure I understand exactly what you’re asking. In my experience, queries _does_ work outside of watch mode; if I use it, my `.graphql` files are used for code generation, but if I omit it, they do not.

That said, I wasn't able to get `--queries=**/*.{graphql, tsx}` to work. Perhaps I’d have better luck targeting both in the `apollo.config.js` 🤔

**Comment by danilobuerger** [comment] 2018-11-16 10:42
@trevor-scheer Was support for `queries` removed on purpose for non-watch?

**Comment by bsunderhus** [comment] 2019-01-24 12:47
I'm running into a similar issue, `--includes=src/**/*.{ts,tsx}` seems to not be working also

**Comment by bsunderhus** [comment] 2019-01-24 12:51
It seems that adding double quotes to the parameter solved the problem in my case

**Comment by trevor-scheer** [comment] 2019-02-07 02:08
@irace is this issue resolved for you? If so, I'd like to close it. Thanks 😄

**Comment by irace** [comment] 2019-02-07 02:27
Admittedly haven’t tried again

**Comment by trevor-scheer** [comment] 2019-02-09 01:05
Ok. I'm going to go ahead and close, but feel free to comment here if you try again and it's not resolved 👍

**Closed by trevor-scheer** 2019-02-09 01:05 UTC

**Comment by cescoferraro** [comment] 2021-03-11 04:06
@trevor-scheer just tried this with 2.32.5 but no luck
