### ISSUE TITLE
Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by wroughtec** [apollographql/apollo-tooling#671] opened 2018-11-08 14:47 UTC
Upgraded 2.0.5 from 1.9.2 which worked (apart from having to delete the `apollo/node_moldules/grapqhl` to get past the `__typename` error). 

Updated the config to take into account the change and am downloading the schema with no issues however run into a problem when generating the query files:

```Loading Apollo Project
 ✔ Saving schema to schema.json
$ apollo codegen:generate --target=flow --useFlowExactObjects --addTypename
 ✔ Loading Apollo Project
 ✖ Generating query files with 'flow' target
   → Cannot convert undefined or null to object
TypeError: Cannot convert undefined or null to object
    at Function.values (<anonymous>)
    at write (~/node_modules/apollo/lib/commands/client/codegen.js:55:55)
    at Task.task (~/node_modules/apollo/lib/commands/client/codegen.js:83:46)
```

Config: 
```
module.exports = {
  client: {
    name: 'Dashboard'
  },
  service: {
    name: 'Dashboard',
    endpoint: {
      url: 'localhost/graphql'
    }
  },
  queries: [
    {
      schema: 'Dashboard',
      includes: ['**/*.graphql'],
      excludes: ['node_modules/**']
    }
  ]
};
```
Is this because I have missed something in the config conversion or is there something else I am missing (perhaps some breaking changes docs should be added to the change log)

**Comment by pheuter** [comment] 2018-11-08 16:45
Getting the same exact error with my config file and codegen command:

```sh
$ apollo client:codegen _graphQL --addTypename --target typescript --globalTypesFile app/types/graphql.ts --queries \"app/**/*.tsx\"
```

```js
module.exports = {
  service: {
    name: "App",
    endpoint: {
      url: "http://localhost:8080/graphql"
    }
  }
};
```

**Comment by clayne11** [comment] 2018-11-10 18:50
I'm having the same issue.

**Comment by bobvanderlinden** [comment] 2018-11-11 14:34
I had the same problem, but figured out from the Typescript definitions how the configuration should be structured. Here is the configuration I used for GitHub:

```
module.exports = {
  client: {
    name: 'GitHubClient',
    service: {
      name: 'GitHub',
      localSchemaFile: 'schema.json'
    },
    includes: ['*.graphql']
  }
};
```

Documentation and validation on this could very much be improved!

A note on one thing that was incorrect in the configurations posted here: the `service:` was placed in the root of the configuration. This makes Apollo use a `GraphQLServiceProject` instead of a `GraphQLClientProject` (even though the client is *also* defined in the config). The `GraphQLServiceProject` does not have a `mergedOperationsAndFragmentsForService`, but the `GraphQLClientProject` does.

**Comment by hlehmann** [comment] 2018-11-14 08:31
@bobvanderlinden the issue I have with your config file is that now  `apollo schema:download --endpoint=...` is now using `localSchemaFile` to generate schema.json :(

**Comment by pajasevi** [comment] 2018-11-15 11:48
I'm having the same issue. Is this a config problem or is the `codegen` script broken?

**Comment by pheuter** [comment] 2018-11-15 15:32
It may be both, but at the very least something is in fact broken because following the README instructions for running `codegen` from a graphql endpoint is consistently throwing the error.

**Comment by trevor-scheer** [comment] 2018-11-15 17:52
@wroughtec

> module.exports = {
>   client: {
>     name: 'Dashboard'
>   },
>   service: {
>     name: 'Dashboard',
>     endpoint: {
>       url: 'localhost/graphql'
>     }
>   },
>   queries: [
>     {
>       schema: 'Dashboard',
>       includes: ['**/*.graphql'],
>       excludes: ['node_modules/**']
>     }
>   ]
> };
> ```
> Is this because I have missed something in the config conversion or is there something else I am missing (perhaps some breaking changes docs should be added to the change log)

Your `queries` key should be flattened into your `client` key like so, there is no queries key in the config:
```
client: {
  name: 'Dashboard',
  includes: ['**/*.graphql'],
  excludes: ['node_modules/**']
}
```

The `config.ts` file is a great reference for now while we tackle issues and improve the documentation:
https://github.com/apollographql/apollo-tooling/blob/master/packages/apollo-language-server/src/config.ts#L64

For all the +1s on this thread, reproductions / links to repos where I can easily reproduce the issue will speed me up drastically and be very much appreciated!

**Comment by lukepighetti** [comment] 2018-11-15 23:46
@trevor-scheer it would be helpful if someone would put together an example config. It is not so easy for beginners to read through type definitions to reverse engineer their own valid config file.

**Comment by bobvanderlinden** [comment] 2018-11-16 10:29
This is an example of usage of schema:download and client:codegen: https://github.com/apollographql/apollo-tooling/issues/671#issuecomment-437675051

For schema:download you do not need any configuration.

For an example of configuration that doesn't use a local schema file you can have a configuration like:

```
module.exports = {
  client: {
    name: 'GitHubClient',
    service: {
      name: 'GitHub',
      url: 'https://api.github.com/graphql',
      headers: {
        'Authorization': 'bearer ***'
      }
    },
    includes: ['*.graphql']
  }
};
```

and execute:

```
apollo client:codegen --target=typescript
```

**Comment by hlehmann** [comment] 2018-11-16 10:57
@bobvanderlinden Thx that way it works!

**Comment by lukepighetti** [comment] 2018-11-16 11:53
@bobvanderlinden Thank you for posting that, it is very helpful. Are there any similar examples for generating types for server side?

**Comment by bobvanderlinden** [comment] 2018-11-16 12:18
I have little experience with graphql, so I'm not sure. I know there is a different configuration (that has `service` as root field instead of `client`), but I haven't used that yet. It is probably worthy of a separate issue though.

**Comment by lukepighetti** [comment] 2018-11-16 20:57
Understood and thank you. For what its worth, I am getting this same error when trying to generate types on the server for type safe resolvers.

**Comment by colinfindlay-nz** [comment] 2018-12-05 22:42
I'm also getting the error trying to do a client:check  (I just wanted to validate queries against a local schema, but maybe I don't understand the usage)

```
module.exports = {
    client: { 
        name: "myClient",
        includes: ['src/queries/**/*.gql'],
        service: {
            name : "myService"
        }
    },
    service: {
        name: "myService",
        localSchemaFile: "./schema.graphql"  
    }
  }
```
As mentioned above this make the check use a `GraphQLServiceProject` which fails.

Trying
```
module.exports = {
    client: { 
        name: "myClient",
        includes: ['src/queries/**/*.gql'],
        service: {
            name : "myService"
            localSchemaFile: "./schema.graphql"  
        }
    }
}
```
Causes the check to try and download the service remotely (i.e. `localSchemaFile` is ignored)

**Comment by treyhuffine** [comment] 2019-01-18 21:09
It's these 2 lines that are breaking for me:

```
const operations = Object.values(this.project.operations);
const fragments = Object.values(this.project.fragments);
```

They are both `undefined` and `Object.values` is erroring

**Comment by frankdugan3** [comment] 2019-01-21 20:32
This is kind of crippling for productivity. Any word on the correct resolution to this issue?

**Comment by mikebm** [comment] 2019-01-21 20:41
> This is kind of crippling for productivity. Any word on the correct resolution to this issue?

I switched over to https://graphql-code-generator.com. Not to take away from this tool, but it is much better, is customizable through plugins and the client side types are more of what you would expect.

**Comment by mikebm** [comment] 2019-01-21 21:32
> Just a heads up with GraphQL Codegen, they use TypeScript `Namespace` which is not compatible with babel. You could get `SyntaxError: Namespaces are not supported.`

You can turn off namespaces in the yml file.

**Comment by treyhuffine** [comment] 2019-01-21 21:32
@mikebm thanks for the tip, going to try that

**Comment by yongnicholaskim** [comment] 2019-04-12 17:58
@bobvanderlinden 

For `service:push` the API says to use `--header=header,` but in the config file, you use the plural:
```
headers: {
  'Authorization': 'bearer ***'
}
```
And it works for you? Alas, neither seems to be working for me.

**Comment by JakeDawkins** [comment] 2019-04-17 16:53
@yongnicholaskim That is because `--header` can be used multiple times to specify multiple headers from the CLI.

As for the other issues in this thread, I _think_ most of them have been solved (at least the original issue). As a summary:

- `apollo client:codegen` ONLY supports CLIENT projects, so if you're trying to use this for codegen of server types, that's completely unsupported right now.
- The config file shape right now has a `config.client.service` key. If you're creating a config with a top-level `service` key and trying to use codegen, you _will_ run into issues (as the cli will treat that config as a service project).
- If you're using a `localSchemaFile`, don't also use a `name`. The `name` is the field that the config looks at for an engine service ID and will try to load a schema from apollo engine instead of the local schema file.

I'm going to close this issue before it goes more off-topic. If there are any remaining issues, just open a new one, please :)

**Closed by JakeDawkins** 2019-04-17 16:53 UTC

**Comment by Cerberus** [comment] 2019-06-20 12:26
I got the same error when provide `ENGINE_API_KEY` in environment.

Now, it's solved. Hope it will helps you too.

FYI: This is a good one for an example setup

https://github.com/abumalick/persisted-queries-showcase

**Comment by just-be-weird** [comment] 2022-05-04 12:18
> `ENGINE_API_KEY`

@Cerberus cheers!! Your comment was big help it fixed the issue. I was in middle of migrating our app which is on v1 of apollo to v3. After upgrade we were greeted with broken devtool.

Steps:
1. Run your application and open your dev console of browser and get the running apollo version by `window.__APOLLO_CLIENT__` you will see your version in output (mine was `version: "3.5.10"`)
2. Copy the version from here and add a new entry in your `.env` file as `ENGINE_API_KEY=3.5.10` and save it
3. Restart the app and the Apollo devtools should get initialized without any errors

**Comment by trevor-scheer** [comment] 2022-05-04 22:31
@just-be-weird im not sure how that did anything for you. The `ENGINE_API_KEY` has nothing to do with your Apollo client version. I think your issue must have resolved itself some other way.

The api key is for users to authenticate the CLI with Apollo Studio.
