### ISSUE TITLE
VSCode: schema validation & error reporting

### ISSUE THREAD

**Issue by borekb** [apollographql/apollo-tooling#1287] opened 2019-05-21 08:27 UTC
If I make typos and other mistakes in `.graphql` files, I'd like to get red squiggly lines and errors in the Problems panel.

**Comment by JakeDawkins** [comment] 2019-07-12 16:32
Hi! Thanks for opening this. Can you be more specific? I think you're asking for better support for service projects and their schemas? I'll mark this as a duplicate of #1026 but if not, please let me know :)

**Closed by JakeDawkins** 2019-07-12 16:32 UTC
Labels: :spiral_notepad: vscode, 👯‍♂️ duplicate
