### ISSUE TITLE
apollo client:push doesn't respect config tag nor --tag argument

### ISSUE THREAD

**Issue by jhalborg** [apollographql/apollo-tooling#994] opened 2019-02-08 09:37 UTC
**Intended outcome:**
I'm trying to push my client queries to Apollo using `client:push`, and expect the CLI to respect 

1. The Apollo Config
2. The `--tag` CLI argument if provided

**Actual outcome:**
Neither the config nor the CLI argument is respected, and the command tries to push to `@current` by default, meaning that `client:push` **cannot be used with schema tags**

**How to reproduce the issue:**
1. Have a service on the Apollo platform
2. Push a schema to a specific tag, i.e. `production`, `beta` etc.
3. Push a different, flawed/older schema to `current`
4. Try to push your client queries to your created tag using the `client:push` command, either by using the config or the `--tag` argument
5. See the push fail, citing errors in the queries against the schema that match the differences between your `current` and `production` schemas.  

**Versions**
Using `apollo` v `2.4.4`. 

**Extra info**
My config:
```
module.exports = {
  client: {
    service: 'myservice@production',
    name: 'react-app',
    version: '1.0.1',
    includes: ['src/**/*.ts', 'src/**/*.tsx', 'src/**/*.graphql'],
  },
  engine: {
    apiKey: '...,
  },
};
```

The commands:
`"apollo-push": "apollo client:push",` or
`"apollo-push": "apollo client:push --tag=\"production\"",`

**Comment by JakeDawkins** [comment] 2019-02-25 15:45
@jhalborg Thanks for bringing this to my attention! Unfortunately, in this version of the operation registry, we don't support operations being tied to a specific `tag`.

That's something we'll be working on with the next version of the registry though. So the solution for the next couple months would be to use the `current` tag for your production services if you're trying to use safelisting.

I've created a couple issues to track this feature and docs updates so you can follow along. Since this is _technically_ by design (and the docs are the actual bug here), I'm gonna close this issue.

**Closed by JakeDawkins** 2019-02-25 15:45 UTC
