### ISSUE TITLE
Unable to resolve project type. Please add either a client or service config.

### ISSUE THREAD

**Issue by atbtechgit** [apollographql/apollo-tooling#901] opened 2019-01-18 20:53 UTC
Receiving error:
`Unable to resolve project type. Please add either a client or service config.`

and

`ENGINE_API_KEY not found`

Here is my apollo.config.js file:
`module.exports = {
  client: {
    service: 'my-service-id',
  },
};`

and .env file:
`ENGINE_API_KEY=service:my-service-439:E4VSTiXeFWaSSBgFWXOiSA`

This did work at some point but decided to break when I loaded up VSCode today.

**Comment by trevor-scheer** [comment] 2019-01-19 00:51
Thanks for taking the time to submit this issue! This is definitely related to some changes we just pushed out, but nothing stands out to me at first glance.

Is there any way you can provide me with a small reproduction case? If not, can you explain your current folder structure with respect to `.env` and `apollo.config.js`? I suspect you've got them at the package root, but just want to make a sanity check here.

**Comment by iquabius** [comment] 2019-01-20 00:08
I'm using this extension on [my project](https://github.com/iquabius/olimat/tree/84be). It's a monorepo managed with Lerna. For some time now I've been using the [multi-root workspace](https://github.com/iquabius/olimat/blob/84be/olimat.code-workspace) feature so that I could get code completion and validation on my GraphQL operations. The `.env` and `apollo.config.js` files are in the subpackage's root:

```
├── api
│   ├── package.json
├── lerna.json
├── olimat.code-workspace
├── package.json
└── web
    ├── apollo.config.js
    ├── .env
    ├── package.json
```
If I opened my project as a folder, I'd only get syntax highlighting (I'm not sure, but I think performance statistics was also working). Hence the need to open it as a workspace in VS Code: completion + validation.

With the new version I noticed code completion is working in both folder and workspace modes. But I
also started getting the same error in both modes: `Unable to resolve project type.` And performance statistics seems to be gone now.

If you want to take a look at the repo you should run `npm install` and `npx lerna bootstrap` to set up dependencies.

Take a look at [this query field](https://github.com/iquabius/olimat/blob/84be/web/src/components/Question/DetailsConnector.tsx#L15). It's getting a type check error because the extension is loading the 'current' tag rather than [the one set in `apollo.config.js`](https://github.com/iquabius/olimat/blob/84be/web/apollo.config.js#L10)

**Comment by AndreasHald** [comment] 2019-02-06 10:42
I'm encountering the same issue using a mono-repo. We have both our server and client in the same repository. But with the `apollo.config.js` file defined as:

`module.exports = {
  client: {
    service: {
      name: 'Aveiro-Server',
      localSchemaFile: './aveiro-server/src/graphql/schema.gql',
    },
  },
};`

I recieve the error `Error: Unable to resolve project type. Please add either a client or service config. For more information`

Anyway to fix this when using mono-repo?

**Comment by hwillson** [comment] 2019-07-12 17:31
Thanks for reporting this issue. We don't currently support multi-root workspaces, but are tracking its addition in https://github.com/apollographql/apollo-tooling/issues/821. Closing here to keep the multi-root discussions in one place.

**Closed by hwillson** 2019-07-12 17:31 UTC
Labels: :spiral_notepad: vscode, 🐞 bug
